### ISSUE TITLE
gradle7.4.2集成失败

### ISSUE THREAD

**Issue by a694190253** [bytedance/CodeLocator#24]
distributionUrl=http\://maven.temu.team/repository/distributions/gradle-7.4.2-bin.zip

ilationFailedException: Compilation failed to complete, origin: /Users/suny/repo/baogong/app/build/intermediates/transforms/lancet/debug/1526.jar:androidx/activity/ComponentActivity$_lancet.class
	at Version.fakeStackEntry(Version_4.0.28.java:0)
	at com.android.tools.r8.utils.ExceptionUtils.failWithFakeEntry(ExceptionUtils.java:139)
	at com.android.tools.r8.utils.ExceptionUtils.failCompilation(ExceptionUtils.java:89)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:83)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:64)
	at com.android.tools.r8.D8.run(D8.java:125)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:115)
	... 40 more
Caused by: java.lang.IllegalArgumentException
	at com.android.tools.r8.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1843)
	at com.android.tools.r8.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at com.android.tools.r8.org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at com.android.tools.r8.org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.android.tools.r8.graph.LazyCfCode.parseCode(LazyCfCode.java:205)
	at com.android.tools.r8.graph.LazyCfCode.internalParseCode(LazyCfCode.java:161)
	at com.android.tools.r8.utils.ExceptionUtils.lambda$withOriginAndPositionAttachmentHandler$5(ExceptionUtils.java:238)
	at com.android.tools.r8.utils.ExceptionUtils.withOriginAndPositionAttachmentHandler(ExceptionUtils.java:246)
	at com.android.tools.r8.utils.ExceptionUtils.withOriginAndPositionAttachmentHandler(ExceptionUtils.java:234)
	at com.android.tools.r8.utils.ExceptionUtils.withOriginAttachmentHandler(ExceptionUtils.java:225)

**Comment by OvenCroc** [comment]
大佬有解决嘛, 我也遇到同样的问题了
